//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ban
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ban()
        {
            this.bxue = new HashSet<bxue>();
        }
    
        public int bid { get; set; }
        public string bname { get; set; }
        public string btext { get; set; }
        public string k1 { get; set; }
        public string k2 { get; set; }
        public string k3 { get; set; }
        public string k4 { get; set; }
        public string k5 { get; set; }
        public string k6 { get; set; }
        public int jid { get; set; }
        public Nullable<System.DateTime> bdate { get; set; }
        public string nian { get; set; }
    
        public virtual kechen kechen { get; set; }
        public virtual kechen kechen1 { get; set; }
        public virtual kechen kechen2 { get; set; }
        public virtual kechen kechen3 { get; set; }
        public virtual kechen kechen4 { get; set; }
        public virtual kechen kechen5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bxue> bxue { get; set; }
        public virtual jiao jiao { get; set; }
    }
}
