//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bchen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bchen()
        {
            this.c1 = 0m;
            this.c2 = 0m;
            this.c3 = 0m;
            this.c4 = 0m;
            this.c5 = 0m;
            this.c6 = 0m;
        }
    
        public string xid { get; set; }
        public int bid { get; set; }
        public decimal c1 { get; set; }
        public decimal c2 { get; set; }
        public decimal c3 { get; set; }
        public decimal c4 { get; set; }
        public decimal c5 { get; set; }
        public decimal c6 { get; set; }
    
        public virtual bxue bxue { get; set; }
    }
}
