//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bxue
    {
        public string xid { get; set; }
        public string xname { get; set; }
        public string xsex { get; set; }
        public System.DateTime xbir { get; set; }
        public int bid { get; set; }
        public string mima { get; set; }
    
        public virtual ban ban { get; set; }
        public virtual bchen bchen { get; set; }
    }
}
