//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fx.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class fxEntities2 : DbContext
    {
        public fxEntities2()
            : base("name=fxEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ban> ban { get; set; }
        public virtual DbSet<bchen> bchen { get; set; }
        public virtual DbSet<bxue> bxue { get; set; }
        public virtual DbSet<jiao> jiao { get; set; }
        public virtual DbSet<kechen> kechen { get; set; }
    
        public virtual ObjectResult<selban_Result> selban(Nullable<int> bid)
        {
            var bidParameter = bid.HasValue ?
                new ObjectParameter("bid", bid) :
                new ObjectParameter("bid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<selban_Result>("selban", bidParameter);
        }
    
        public virtual ObjectResult<bandb_Result> bandb(Nullable<int> bid)
        {
            var bidParameter = bid.HasValue ?
                new ObjectParameter("bid", bid) :
                new ObjectParameter("bid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<bandb_Result>("bandb", bidParameter);
        }
    
        public virtual ObjectResult<string> bxinx(Nullable<int> bid)
        {
            var bidParameter = bid.HasValue ?
                new ObjectParameter("bid", bid) :
                new ObjectParameter("bid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("bxinx", bidParameter);
        }
    
        public virtual ObjectResult<fenshu_Result> fenshu(Nullable<int> bid)
        {
            var bidParameter = bid.HasValue ?
                new ObjectParameter("bid", bid) :
                new ObjectParameter("bid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<fenshu_Result>("fenshu", bidParameter);
        }
    
        public virtual ObjectResult<fentop_Result> fentop(Nullable<int> bid)
        {
            var bidParameter = bid.HasValue ?
                new ObjectParameter("bid", bid) :
                new ObjectParameter("bid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<fentop_Result>("fentop", bidParameter);
        }
    
        public virtual ObjectResult<kemu_Result> kemu(Nullable<int> bid)
        {
            var bidParameter = bid.HasValue ?
                new ObjectParameter("bid", bid) :
                new ObjectParameter("bid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<kemu_Result>("kemu", bidParameter);
        }
    
        public virtual ObjectResult<zhan_Result> zhan(Nullable<int> bid)
        {
            var bidParameter = bid.HasValue ?
                new ObjectParameter("bid", bid) :
                new ObjectParameter("bid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<zhan_Result>("zhan", bidParameter);
        }
    }
}
